### PR TITLE
added pictures with width 400px 

### PR DESCRIPTION
**Pull request by pinak22dhir**
have a look on issue #33

### CODE REVIEW

**Comment by SohamKukreti** [comment]
The pictures look good 👍 but it would better if you could create a new section for the images after the general info section.
image

and also, no need for this image:
image

**Comment by pinak22dhir** [comment]
Resolved issue #33 , now look

**Comment by SohamKukreti** [comment]
Also one final thing, can you make this the first image?

image

**Comment by pinak22dhir** [comment]
sure @SohamKukreti  kindly add kwoc tag on the issue

**Comment by SohamKukreti** [comment]
Okay

**Comment by pinak22dhir** [comment]
@SohamKukreti   please see now

**Comment by SohamKukreti** [comment]
> @SohamKukreti please see now

LGTM 👍

**Pull request merged**
